### ISSUE TITLE
why did you strip the copyright?

### ISSUE THREAD

**Issue by ITotalJustice** [DeeSEmu/DeeS#1]
the emulator is [NooDS](https://github.com/Hydr8gon/NooDS) and all source files had copyright at the top. With all the copyright removed, it makes this project a little misleading in the sense that it looks like you are the author of the code, especially as there is no mention of NooDS anywhere.

i think you should at the copyright back and give a mention somewhere that the core is NooDS.

**Comment by official-antique** [comment]
I'll be doing exactly that however, I'm planning on doing a full rewrite anyway as there are some issues with the code and improvements that could be made.

**Comment by fleroviux** [comment]
I sure hope by 'doing a full rewrite' you mean writing an original core from scratch, not rewriting the NooDS core or otherwise heavily basing on it. Either way it isn't a good look to point out issues or room for improvements in code that was good enough for you to take it without appropriate credit.
